/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import conexao.Conexao;
import conexao.ConexaoPSQL;
import dados.Consulta;
import dados.Medico;
import dados.Paciente;
import dados.TipoConsulta;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos.MetConsulta;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Vinnen
 */
public class FormConsultaList extends javax.swing.JFrame {
    
    public FormConsultaList() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_consulta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jT_data = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lista.png"))); // NOI18N
        jLabel1.setText(" Lista de Consultas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jT_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Horário", "Status", "ID Paciente", "Paciente", "ID Médico", "Médico", "ID Consulta", "Consulta", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jT_consulta);

        jLabel2.setText("Pesquisar Por Data: ");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/imprimir.png"))); // NOI18N
        jButton3.setText("Imprimir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        try {
            jT_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jT_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_dataActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fechar.png"))); // NOI18N
        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/atualizar.png"))); // NOI18N
        jButton5.setText("Atualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        jButton6.setText("Pesquisar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/agendar.png"))); // NOI18N
        jButton7.setText("Agendar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jT_data, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jT_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int opcao = jT_consulta.getSelectedRow();
        if (opcao >= 0) {
            Consulta c = new Consulta();
            c.setId_consulta(Integer.parseInt(jT_consulta.getValueAt(opcao, 0).toString()));            
            MetConsulta metc = new MetConsulta();
            metc.excluir(c);
            preencherTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um linha!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int opcao = jT_consulta.getSelectedRow();
        if (opcao >= 0) {
            Consulta c = new Consulta();
            c.setId_consulta(Integer.parseInt(jT_consulta.getValueAt(opcao, 0).toString()));
            c.setData(jT_consulta.getValueAt(opcao, 1).toString());
            c.setHora(jT_consulta.getValueAt(opcao, 2).toString());
            c.setStatus(jT_consulta.getValueAt(opcao, 3).toString());
            
            Paciente p = new Paciente();
            p.setId_paciente(Integer.parseInt(jT_consulta.getValueAt(opcao,4).toString()));
            p.setNome(jT_consulta.getValueAt(opcao, 5).toString());
            c.setPac(p);
            
            Medico m = new Medico();
            m.setId_medico(Integer.parseInt(jT_consulta.getValueAt(opcao, 6).toString()));
            m.setNome(jT_consulta.getValueAt(opcao, 7).toString());
            c.setMed(m);
             
            TipoConsulta tp = new TipoConsulta();
            tp.setId_tipoConsulta(Integer.parseInt(jT_consulta.getValueAt(opcao, 8).toString()));
            tp.setTipo_consulta(jT_consulta.getValueAt(opcao, 9).toString());
            tp.setValor(jT_consulta.getValueAt(opcao, 10).toString());
            c.setTipcon(tp);
            
            FormConsulta fc = new FormConsulta(c);
            fc.setVisible(true);    
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um linha!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jT_data.setText(null);
        preencherTabela();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        FormConsulta fc = new FormConsulta();
        fc.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        preencherTabela(jT_data.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                String sql = "SELECT\n" +
"     *,\n" +
"     paciente.\"pac_id\" AS paciente_pac_id,\n" +
"     paciente.\"pac_nome\" AS paciente_pac_nome,\n" +
"     medico.\"med_id\" AS medico_med_id,\n" +
"     medico.\"med_nome\" AS medico_med_nome,\n" +
"     tipoconsulta.\"tipcon_id\" AS tipoconsulta_tipcon_id,\n" +
"     tipoconsulta.\"tipcon_tipo\" AS tipoconsulta_tipcon_tipo,\n" +
"     tipoconsulta.\"tipcon_valor\" AS tipoconsulta_tipcon_valor,\n" +
"     consulta.\"cons_id\" AS consulta_cons_id,\n" +
"     consulta.\"cons_data\" AS consulta_cons_data,\n" +
"     consulta.\"cons_horario\" AS consulta_cons_horario,\n" +
"     consulta.\"cons_status\" AS consulta_cons_status\n" +
"FROM\n" +
"     \"paciente\" paciente INNER JOIN \"consulta\" consulta ON paciente.\"pac_id\" = consulta.\"pac_id\"\n" +
"     INNER JOIN \"medico\" medico ON consulta.\"med_id\" = medico.\"med_id\"\n" +
"     INNER JOIN \"tipoconsulta\" tipoconsulta ON consulta.\"tipcon_id\" = tipoconsulta.\"tipcon_id\"";
        try{
            Map param = new HashMap();
            Connection con = ConexaoPSQL.dbConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet resultado = pst.executeQuery();
            JRResultSetDataSource relatConsult = new JRResultSetDataSource(resultado);
            JasperDesign jdesign = JRXmlLoader.load("C:\\Users\\Vinnen\\Documents\\NetBeansProjects\\ProjetoConsultorioPostgreSQL\\src\\relatorios\\relatorio_consulta.jrxml");
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jpPrint = JasperFillManager.fillReport(jreport, param, relatConsult);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro ao imprimir!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jT_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_dataActionPerformed
        preencherTabela(jT_data.getText());
    }//GEN-LAST:event_jT_dataActionPerformed

    public void preencherTabela() {
        MetConsulta metc = new MetConsulta();
        List<Consulta> lista = metc.ListarTodos();
        DefaultTableModel modeloTabela = (DefaultTableModel) jT_consulta.getModel();
        modeloTabela.setRowCount(0);
        for (Consulta c : lista) {
            modeloTabela.addRow(new Object[]{c.getId_consulta(), c.getData(), c.getHora(), c.getStatus(), c.getPac().getId_paciente(), c.getPac().getNome(), c.getMed().getId_medico(), c.getMed().getNome(), c.getTipcon().getId_tipoConsulta(), c.getTipcon().getTipo_consulta(), c.getTipcon().getValor()});
        }
    }
    
    public void preencherTabela(String data) {
        MetConsulta metc = new MetConsulta();
        List<Consulta> lista = metc.ListarData(data);
        DefaultTableModel modeloTabela = (DefaultTableModel) jT_consulta.getModel();
        modeloTabela.setRowCount(0);
        for (Consulta c : lista) {
            modeloTabela.addRow(new Object[]{c.getId_consulta(), c.getData(), c.getHora(), c.getStatus(), c.getPac().getId_paciente(), c.getPac().getNome(), c.getMed().getId_medico(), c.getMed().getNome(), c.getTipcon().getId_tipoConsulta(), c.getTipcon().getTipo_consulta(), c.getTipcon().getValor()});
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultaList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultaList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultaList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultaList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultaList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_consulta;
    private javax.swing.JFormattedTextField jT_data;
    // End of variables declaration//GEN-END:variables
}
